# Generated by Django 5.2.9 on 2025-12-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_student_number_students_student_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="student_id",
            new_name="student_number",
        ),
    ]
