# Generated by Django 5.2.9 on 2025-12-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_rename_student_id_students_student_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="student_number",
            new_name="student_id",
        ),
    ]
