# Generated by Django 5.2.9 on 2025-12-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_rename_student_number_students_student_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Students",
            new_name="Student",
        ),
    ]
