# Generated by Django 5.2.9 on 2025-12-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_number',
        ),
    ]
